### ISSUE TITLE
Option to connect on HTTP not HTTPS

### ISSUE THREAD

**Issue by dubravcik** [gouline/dbt-metabase#1]
Could you please add an option to connect to metabase API with HTTP ? Currently HTTPS is required.

**Comment by gouline** [comment]
Thanks for raising this. Sure, it's pretty simple to do, I'll aim to release a version this week.

**Comment by gouline** [comment]
Got around to it quicker than expected. You can find `mb_https` argument in https://github.com/gouline/dbt-metabase/releases/tag/v0.1.5.

Leaving it off the documentation (other than command-line help) because the practice of running Metabase on HTTP is not recommended.
