### ISSUE TITLE
Support for Metabase timeline events

### ISSUE THREAD

**Issue by ValdarT** [gouline/dbt-metabase#101]
Support for [timeline events](https://www.metabase.com/docs/latest/users-guide/events-and-timelines) would be cool ([API](https://www.metabase.com/docs/latest/api/timeline-event.html)).

**Comment by gouline** [comment]
What kind of support do you envision? Not sure I understand how you'd set timeline events from dbt schema.

**Comment by ValdarT** [comment]
> Not sure I understand how you'd set timeline events from dbt schema.

I'd propose listing in [meta](https://docs.getdbt.com/reference/resource-configs/meta) conf. (It'd obviously be specific to `dbt-metabase` as it's to support a Metabase-specific feature). The point is to be able to manage such metadata along with other such as documentation in a central place (dbt).

**Comment by gouline** [comment]
What would that look like?

Meta config is defined on dbt models or columns, whereas events and timelines belong to Metabase questions.

**Comment by ValdarT** [comment]
Yes, the data itself should be stored separately but linked to the timeline through the `meta` config. I guess it could work by either designating the columns to use in the conf or requiring a certain format and then specifying only the timeline details for the API calls. The latter - requiring certain format - could work well with a [seed](https://docs.getdbt.com/docs/build/seeds), perhaps?

**Comment by gouline** [comment]
That feels like misuse to force a feature not supported by dbt. If they ever implement it, I'll revisit this proposal, but for now I'd encourage you to start a separate project.

**Comment by ValdarT** [comment]
I understand the sentiment. Note that it's not unusual to extend the dbt functionality like this, though. For example: [elementary-data](https://docs.elementary-data.com/oss/guides/alerts-configuration).
