### ISSUE TITLE
dbt database not being read properly / readme instructions not clear in next steps

### ISSUE THREAD

**Issue by brad-mcglynn** [gouline/dbt-metabase#105]
Whether I try dbt-metabase programmatically or with CLI, each time it seems that it cannot find the appropriate database to reference. I could put any string there or even leave it as a blank string and the same issue arises; nothing is being read.

Is this the correct way to load these variables? The DbtInterface seems to be the only portion not funcitoning properly, but I'm unsure how exactly to resolve the issue of it not reading things properly

```py
dbt = DbtInterface(
    path='/home/bradmcglynn/vm_dbt_package/rvezy-dbt-1/models/reports/dimensions',
    manifest_path='/home/bradmcglynn/vm_dbt_package/rvezy-dbt-1/target/manifest.json',
    database='rvezy-1379',
    schema='dimensions.yml',
    schema_excludes=None,
    #includes=dbt_includes,
    excludes=None,
)
```

**Comment by gouline** [comment]
It's documented in the class [constructor](https://github.com/gouline/dbt-metabase/blob/275a72dac489916479ed1309c837206db329ec9d/dbtmetabase/models/interface.py#L113-L119). Only specify `path` or `manifest_path` (not both) and `schema` is the name of your database schema, not a YAML file. Optional arguments don't need `None`, just omit them.
