### ISSUE TITLE
TypeError: exposures() got an unexpected keyword argument 'metabase_session_id'

### ISSUE THREAD

**Issue by aloysius-chow** [gouline/dbt-metabase#124]
Seems like there was a commit to add `metabase_session_id` as a CLI option, but it was added as a parameter only for `model` and not for `exposures`. Adding the corresponding lines to `exposures` resolved the issue for me.

**Comment by gouline** [comment]
@aloysius-chow Sounds about right, can you PR this change? Should be pretty small.

**Comment by aloy99** [comment]
Have created a PR from my personal (non-work) account here: https://github.com/gouline/dbt-metabase/pull/127
