### ISSUE TITLE
Model meta metabase.display_name not parsed

### ISSUE THREAD

**Issue by willbryant** [gouline/dbt-metabase#129]
The `export_model` function supports setting the display name for models from a `display_name` property on `MetabaseModel`.

However, this isn't accessible, as the `meta:` `metabase.display_name` property is not parsed and populated in the construction of the `MetabaseModel` in `_read_model`.

**Comment by willbryant** [comment]
Wait, you added it in August. So why isn't it working, hmm.

**Comment by willbryant** [comment]
Ah no, it's only in dbt_folder.py, the equivalent code is missing from dbt_manifest.py.

**Comment by gouline** [comment]
Sounds like you already found the fix, happy to raise a PR?

**Comment by willbryant** [comment]
There ya go :)

**Comment by willbryant** [comment]
Actually, would a better fix be to add display_name to METABASE_META_FIELDS?

At the moment display_name doesn't work for columns, for sort of similar reasons. If I add display_name there, I believe it will fix columns, but it also makes the explicit code for display_name unnecessary?

**Comment by willbryant** [comment]
Yeah, that seems to work better, update the PR.
