### ISSUE TITLE
Clearing an automatic metabase.semantic_type

### ISSUE THREAD

**Issue by willbryant** [gouline/dbt-metabase#131]
In 646a914009bdfcfbc7c4c36a377a79d7435c73da, you fixed it so that if we haven't specified a metabase.semantic_type.

This is good, but now, how do we explicitly clear a semantic type set by the automagic rules that Metabase applies on schema sync?

Setting `metabase.semantic_type: null` seems to have no effect. Can we look for the presence of this key, or maybe use a special value?

**Comment by gouline** [comment]
What value does the API return if you manually clear it in the UI? Is it just null?

**Comment by willbryant** [comment]
Python `None`, which is `null` right?

**Comment by gouline** [comment]
That's tricky then, the expected behaviour is unless you specify one (or specify null - same result), it doesn't touch what Metabase currently has. So to implement what you want, you would need to invent an explicit null value. I'll think about it.

**Comment by willbryant** [comment]
FWIW YAML knows the difference between null and "not present in map", so IMHO the explicit null value could be purely internal.

**Comment by gouline** [comment]
Agreed. Looking at that code now, I might take this opportunity to refactor around it a bit, so I'll fix it.
