### ISSUE TITLE
Password env var name

### ISSUE THREAD

**Issue by willbryant** [gouline/dbt-metabase#133]
Not clear what the env var should be called. Readme and first place in the code says MB_PASS:

```
ENV_VARS = [
    "DBT_DATABASE",
    "DBT_PATH",
    "DBT_MANIFEST_PATH",
    "MB_USER",
    "MB_PASS",
```

But the actual env var handling code says:

```
    "DBT_PATH",
    "DBT_MANIFEST_PATH",
    "MB_USER",
    "MB_PASS",

    @click.option(
        "--metabase_password",
        metavar="PASS",
        envvar="MB_PASSWORD",
```

Is the latter wrong?

**Comment by gouline** [comment]
Not sure either one even works, they seem to exclude each other. It should be `MB_PASSWORD` if you feel like doing a quick PR.
