### ISSUE TITLE
Schema option case sensitivity

### ISSUE THREAD

**Issue by willbryant** [gouline/dbt-metabase#140]
Docs say you can use:

```
    dbt_schema_excludes:
      - development
      - testing
```

And there's also support for a `--dbt_schema_excludes` command-line option.

However, you must actually upcase the schema name, unlike the example before, because the code that actually looks at this is:

```
if schema_excludes and node["schema"].upper() in schema_excludes:
```

I'm not really clear why the `upper()` is there. If it's just for the sake of normalising, then we also need to normalise the arguments?

**Comment by gouline** [comment]
That's a bug. The point was to make them case insensitive, except it's forgetting to first make `schema_excludes` all the same case. The parameters `includes` and `excludes` are a good example, except they're inconsistent between manifest and folder parsers too. I'll look into making all three consistent.
