### ISSUE TITLE
Model visibility not synchronized 

### ISSUE THREAD

**Issue by ArthurdeVries** [gouline/dbt-metabase#146]
**Description**
I have issues with transferring the `visibility` on a model level towards Metabase. While the `visibility` of the model is defined in the dbt `.yml` file, it is not synchronized towards Metabase. I've tested it with multiple `visibility` types and changed the description as well to verify that the connection works. The log also shows the models are updated successfully. Does someone know what I might be doing wrong here?

**Example**
![Screenshot 2022-09-19 at 11 48 35](https://user-images.githubusercontent.com/50827089/190992311-6f1044cc-bc3c-4a75-b68f-b90c46e86f15.png)

**Versions**
dbt-metabase: `0.9.6`
metabase: `0.43.4`

I hope someone is able to assist me, if extra information is necessary I am more than happy to supply it.

**Comment by ArthurdeVries** [comment]
@gouline tagging you as you are the owner of this repository. Do you know if this can be checked out? Or how we could possibly solve this ourselves? It would be a great addition if this worked!

**Comment by gouline** [comment]
Try the latest version, I vaguely remember some work being done on this since 0.9.6.

**Comment by ArthurdeVries** [comment]
Did not get version `0.9.14` working, using `0.9.13` the visibility was synchronized. Closing.
