### ISSUE TITLE
Models in separate schema raise loud error messages

### ISSUE THREAD

**Issue by JonCrawford** [gouline/dbt-metabase#156]
When I run the `models` command, I get 100+ error messages that look like the image below. These models are not in the primary `analytics` schema but rather a `analytics_support` schema. There should be a way to dynamically define the schema based on the model.

![schema error messages](https://p191.p3.n0.cdn.getcloudapp.com/items/12uRzOXA/6fd1923f-b4e5-4f21-9f32-258150bca549.png?v=8436ae922a51721cd80eaed7bfbd813b)

**Comment by gouline** [comment]
That's supported if you use the manifest parsing (not folder parsing) https://github.com/gouline/dbt-metabase#1-artifacts
