### ISSUE TITLE
Making exposures output idempotent

### ISSUE THREAD

**Issue by ernesto-jimenez** [gouline/dbt-metabase#165]
Running the command twice changes the exposures file due to changes in the order of the outputs.

This results in noisy diffs which make it harder to follow what changed.

Proposal: When preparing the output, sort all arrays alphabetically.

**Comment by gouline** [comment]
I'm happy with the suggested approach. However, I'm not using the exposure functionality myself, that entire area of the codebase was contributed by the community. As a result, you (or somebody else interested) will have to work on that and contribute yourself.
