### ISSUE TITLE
Upgrade to v0.9.11 from v0.9.10 introduces timeout exception

### ISSUE THREAD

**Issue by DustyShap** [gouline/dbt-metabase#167]
I can run the dbt-metabase models command on v0.9.10 and it runs as expected.  If I bump to v0.9.11, I encounter a timeout (using the exact same command/arguments).

```requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='our.metabase.host', port=443): Read timed out. (read timeout=30)```

Metabase v0.46.1
dbt-core version 1.4.6

**Comment by gouline** [comment]
That's intended behaviour, no timeouts means it can hang forever. There have been improvements in API request performance in more recent versions though, so try migrating to the latest and if you are still encountering timeouts, we can look into what can be made configurable there. Older versions (like 0.9.11) will not be patched.

**Comment by gouline** [comment]
How long does that request actually take?

**Comment by gouline** [comment]
Timeout is current 15s, if the request took 5-10s, it wouldn't time out. There is currently no way to override it, but depending on how long your Metabase API request that times out actually takes, I'll decide between just raising the timeout (easier) or adding configuration (harder).
