### ISSUE TITLE
dbt docs not syncing across to Metabase - only Jinja templates are showing

### ISSUE THREAD

**Issue by meenaparam** [gouline/dbt-metabase#169]
Hello,

I was using dbt-metabase v.0.9.15 with dbt v.1.5.0. Everything was working well - great package, thank you!

Until suddenly dbt docs were no longer pulling through to Metabase. Everything is working fine within dbt i.e. running `dbt docs serve` shows correct documentation for models. But the equivalent docs no longer appear in Metabase - instead I only see the Jinja templating (see screenshot).

I downgraded to v0.9.13 but I get the same issue. At least with v.0.9.13 the run completes successfully. With v.0.9.15 I get the issue #167.

I'm executing dbt-metabase from the command line:

```
dbt-metabase models \
--dbt_path . \
--dbt_database snowflake  \
--metabase_host XXXX.metabaseapp.com \
--metabase_user XXXX \
--metabase_password XXXXX \
--metabase_database analytics \
--dbt_schema analytics_silver
```

Is this is a known issue about docs not syncing across?

Thanks for the help!

![Screenshot 2023-05-31 at 15 20 15](https://github.com/gouline/dbt-metabase/assets/7209522/87335acc-7ba5-4a99-ad30-00e3bfb308e5)

**Comment by gouline** [comment]
Could this be related to #148?

**Comment by meenaparam** [comment]
> Could this be related to #148?

Hey @gouline thanks for the reply. I don't think it's related as dbt-metabase was working totally fine for me until a week ago, an I've always used jinja templating in my dbt docs. I'll keep an eye on #148 anyway, but I think this is a separate problem, based on the recent timing of my issue.
