### ISSUE TITLE
Propagate dbt analyses to Metabase

### ISSUE THREAD

**Issue by keurcien** [gouline/dbt-metabase#170]
Thanks for the great package, it gives a lot of ideas!

One of the questions I have, is whether you have considered to propagate dbt analyses as Metabase cards?
It would be great to be able to have a collection of cards that have been versioned with dbt. 

I believe the general idea would be to have a 1-to-1 mapping between an analysis and a Metabase card, and a solution could look like this:

- parse the `manifest.json` to look for exposures.
- have a way to identify that an exposure is a Metabase card (maybe in the way the exposure name is defined, e.g add a prefix to parse, `- name: MB117 - ....` for the 117th card in Metabase)
- the `depends_on` should be a ref to a unique analysis
- get the analysis SQL and update the card `dataset_query` property.

N.B: I know analyses aren't refable: [issue](https://github.com/dbt-labs/dbt-core/issues/7127), but the idea remains the same using ephemeral models that could be stored in a `metabase` or `metabase_cards` subfolder. If this looks like an interesting feature, I'd love to contribute if needed.

**Comment by gouline** [comment]
Sounds interesting, would love to see a draft of this implementation.
