### ISSUE TITLE
Configure API timeout for calls made to Metabase

### ISSUE THREAD

**Issue by rishabh-oswal-medbelle** [gouline/dbt-metabase#179]
Currently all calls are made to the Metabase API using the function api() defined on line 961 in dbtmetabase/metabase.py.

When any API is called below is the code executed
`response = self.session.request(
            method,
            f"{self.base_url}{path}",
            timeout=15,
            **kwargs,
        )`
        
So for eg. when the database/{id}/metadata?include_hidden=True is executed there is a timeout for only 15 seconds.

We have a lot of tables in our database and this operation alone is taking almost 2 minutes to complete.

We always face this 15 seconds timeout and are not able to proceed and update any metadata on Metabase from DBT.

Will this require a code fix or is there a workaround I could use.

Link: https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/metabase.py#L961

**Comment by gouline** [comment]
It's currently not configurable, see discussion in https://github.com/gouline/dbt-metabase/issues/167#issuecomment-1548654780_. Easiest fix would be to bump it up, but I would only be comfortable with up to a minute. Anything higher than that, you'd have to make it configurable.

**Comment by rishabh-oswal-medbelle** [comment]
My API is taking almost 2 minutes to respond to the endpoint I mentioned above.

**Comment by pquadri** [comment]
same here, I can manually disable it while working locally but i'd like it to be configurable :) (i can also take this on)
