### ISSUE TITLE
Accept True in the --metabase_verify option to default to the default CAs. 

### ISSUE THREAD

**Issue by SergioPiriz** [gouline/dbt-metabase#185]
When Metabase is hosted on a DNS using a certificate signed by a recognised authority it would be great not to see all those warning without supplying the actual certificate bundle path. 

It would be great to be able to pass True on the verify option to verify using the system default CA.

**Comment by pquadri** [comment]
just a heads up, i disabled it by setting  PYTHONWARNINGS to "ignore:Unverified HTTPS request" (only for the specific job where i use this library)

**Comment by gouline** [comment]
These parameters will change in the upcoming 1.0 release, which should resolve this issue.
