### ISSUE TITLE
Requests failing due to "include_hidden" not being valid boolean string

### ISSUE THREAD

**Issue by wdtrott** [gouline/dbt-metabase#198]
Platform details:
Metabase version: v1.48.0
dbt-metabase version: v0.10.1

My team is encountering the following error when trying to export models through a python script: 

```
HTTP request failed. Payload: None. 
Response: {"errors":{"include_hidden":"nullable value must be a valid boolean string ('true' or 'false')."},
"specific-errors":{"include_hidden": must be a valid boolean string ('true' or 'false')., received: \"True\""]}}
```

We are using an almost direct copy of what is in the readme, and have been syncing successfully for the past month. Based on the error, the issue appears to stem from [this line](https://github.com/gouline/dbt-metabase/blob/b6874a744a6cd861ef4bc84dd44c50d9e8718601/dbtmetabase/metabase.py#L368) in the `_load_tables` method.

**Comment by gouline** [comment]
Interesting, I didn't realise GET params in requests don't get properly serialised to string. Fixed in 0.10.2.
