### ISSUE TITLE
--metabase_exclude_sources - Doesn't work after release

### ISSUE THREAD

**Issue by KonradA-survi** [gouline/dbt-metabase#225]
hey, we used the --metabase_exclude_sources function, thanks to which everything worked for us, but 3 weeks ago after the release, this function stopped working and we were unable to replace it with anything, and we still have problems with connecting to the dbt metabase. Is there any new solution for this function?

part of our workflow:
     - run: pip install dbt-metabase

    - name: dbt deps
      run: dbt deps

    - name: dbt compile
      run: dbt compile
    
    - name: dbt-metabase
      run: dbt-metabase models --verbose --metabase_exclude_sources
      env:
        MB_PASSWORD: ${{ secrets.MB_PASSWORD }}
        DBT_DATABASE: ${{ vars.DBT_DATABASE }}
        DBT_MANIFEST_PATH: ${{ vars.DBT_MANIFEST_PATH }}
        MB_USER: ${{ vars.MB_USER }}
        MB_HOST: ${{ vars.MB_HOST }}
        MB_DATABASE: ${{ vars.MB_DATABASE }}

**Comment by gouline** [comment]
That flag was renamed to `--skip-sources` along with several other renames in v1.0. Please run `dbt-metabase models --help` to see all currently supported flags and environment variables.
