### ISSUE TITLE
Add option for choosing continuation strategy for when models or fields are not synced

### ISSUE THREAD

**Issue by ewhauser** [gouline/dbt-metabase#231]
`dbtmetabase` just errors if it can't find a model or a field. In some cases, it would be preferred to just sync the models and fields that can be synced and skip over ones that don't exist yet

**Comment by gouline** [comment]
> If you have known discrepancies between dbt and Metabase and wish to proceed without synchronization, set the sync timeout to zero (e.g. `--sync-timeout 0`).

https://github.com/gouline/dbt-metabase#synchronization
