### ISSUE TITLE
Add wildcard syntax to table filters

### ISSUE THREAD

**Issue by ewhauser** [gouline/dbt-metabase#232]
Certain models - such as staging tables - might not be a part of Metabase's table definitions. As opposed to having to specify all includes or excludes, `dbtmetabase` should allow you to define a wildcard to exclude them, i.e.

```python
        c.export_models(
            metabase_database="my_database",
            schema_filter=Filter(include=["PUBLIC", "SNAPSHOTS"], exclude=["STG_*"]),
            skip_sources=True,
        )
```

**Comment by gouline** [comment]
Good point, I've thought about implementing this before.
