### ISSUE TITLE
Exposure Extraction Error | In Case of Missing Cards in collection

### ISSUE THREAD

**Issue by dosnep** [gouline/dbt-metabase#237]
**Context:** 

When I use Metabase API to delete archived cards, it creates inconsistency because card are still referenced in collections.
So [at this step](https://github.com/gouline/dbt-metabase/blob/9fc8bcd67e6f418bb45561c238c8ffa6dd9dfb49/dbtmetabase/_exposures.py#L98C6-L98C68), it's possible to search a deleted card/dashboard causing an HTTP code 400 error and makes application crash.

**Problem**

In case of inconsistency between collections and cards/dashboards, dbt-metabase will crash because it tries to query a missing card/dashboard. 

**Request**

Skip a card/dashboard which is referenced in a collection but has been deleted.

**Technical Solution**

Test for each items in a Collection if the associated resource is reachable otherwise continue to the next item.
We could add a try&catch statement for get_dashboard and get_card as we did [here](https://github.com/gouline/dbt-metabase/blob/9fc8bcd67e6f418bb45561c238c8ffa6dd9dfb49/dbtmetabase/metabase.py#L166)

**Note**

Event if it's not the purpose of that tool, it could be interresting to highlight inconsistency with the logger in case of unreachable item resource.

**Comment by gouline** [comment]
I'm surprised Metabase still lists deleted cards and dashboards. Does this happen on the latest version? If so, should this be reported to Metabase as a bug too?

**Comment by dosnep** [comment]
I'm working with an old version (0.45.4.3), definitely, we should try with the latest, I'll work on that in best effort and let you know about it.
Additionally, I tried to find directly in the database if we have a table that stores mapping between collection_id and card_id (and a delete on cascade configured on the card table for the card_id pk) but no table like that, It seams that this logic is handle directly by the application (consistency as well).

**Comment by gouline** [comment]
Assuming you're deleting cards with [`DELETE /api/card/:id`](https://www.metabase.com/docs/v0.45/api/card#delete-apicardid):
> DEPRECATED – don’t delete a Card anymore – archive it instead.

You can finish #238 for extra safety, but I'm closing the issue as invalid, because this is unsupported by Metabase.
