### ISSUE TITLE
"Display values" in a foreign key

### ISSUE THREAD

**Issue by radium226** [gouline/dbt-metabase#245]
Hello! 

First of all, thanks a lot for this piece of software. It works great and help me a lot to propagate the docs between DBT and Metabase! 

I was wondering how difficult it would be to add the possibility to set the "Display values" value when using a foreign keys between two tables (you can see this parameter when clicking on the small gear on left of a field in the Table Metadata). 

I'm willing to help implement this, but I think you should show me where to start :)

Thanks!

**Comment by gouline** [comment]
It's reasonably difficult.

Easy part is setting the target field name as another column meta field (similar to `semantic_type`), but then you have to look up its corresponding field ID and create a new kind of delayed update (similar to `table_field_order`) that calls [POST /api/field/:id/dimension](https://www.metabase.com/docs/latest/api/field#post-apifieldiddimension) with the field ID as `human_readable_field_id`.

Not sure how doable that is for a first contribution to an unfamiliar codebase to be honest.
