### ISSUE TITLE
HTTP Timeouts, how do I increase the timeout?

### ISSUE THREAD

**Issue by bulatyapparov** [gouline/dbt-metabase#247]
Metabase Log:
> [ece09e30-387a-44c2-84c2-d3e3d2fe3ff0] 2024-03-28T17:11:54+00:00 INFO metabase.server.middleware.exceptions Request canceled before finishing.

Shell output:
```shell
INFO     2024-03-28 17:11:19 +0000 — Metabase session established                                                          metabase.py:55
WARNING  2024-03-28 17:11:42 +0000 — Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) connectionpool.py:824
         after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='xxx, port=443):                        
         Read timed out. (read timeout=15)")': /api/database/16/metadata?include_hidden=true          
```

**Comment by bulatyapparov** [comment]
that works, thank you!

would be great to have this explained in the readme.

**Comment by alex-float-on** [comment]
`dbt-metabase models --help` will show you all the flag options.

If you want to contribute, you can always open a PR to expand the `README.md` 👍
