### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by alexisflipo** [gouline/dbt-metabase#252]
Hello,

Since a few days we observed this error on Airflow:

```
File "/home/airflow/.venv/lib/python3.9/site-packages/dbtmetabase/parsers/dbt_manifest.py", line 207, in _read_model
    is_incoming_relationship_test = depends_on_nodes[1] != unique_id
IndexError: list index out of range
```

We can't find from which dbt model it comes from. We have a lot of PR that are merged daily with modifications on models and its descriptions. Do you know how I can find the root cause or have an info in the the logs please ?

**Comment by gouline** [comment]
You are running an old version, this issue was fixed in 1.0.0 (#210) and even backported to 0.10.3 (#211).
