### ISSUE TITLE
Exposures have no dependencies. depends_on arrays are empty

### ISSUE THREAD

**Issue by ampersand-five** [gouline/dbt-metabase#260]
I updated dbt-metabase from 1.0.1 to 1.3.1 and after doing that when I run exposures, all the depends_on arrays are now empty, where as before they were not. Which makes the dependency graph flat now, i.e. broken.

Any ideas as to why the depends_on in exposures is now not populating?

**Comment by gouline** [comment]
Tests are passing, so I need more information to reproduce this, e.g. dbt version, Metabase version, database and preferably a minimal sample repo that exhibits the issue (without anything proprietary).

Can you also try other versions between 1.0.1 and 1.3.1 to narrow down when the bug was introduced?

**Comment by ampersand-five** [comment]
1)
python = "3.10"
dbt-snowflake = "1.7.1"
dbt-metabase = "1.3.1"
dbt-core = "1.7.6"

2) Metabase 1.49.14
3) Snowflake
4) A full exposure dump, so all of them?

Other versions:
- Dependencies work up to dbt-metabase 1.1.0 for me. After that, the dependencies stop populating.

**Comment by gouline** [comment]
> Dependencies work up to dbt-metabase 1.1.0 for me. After that, the dependencies stop populating.

Are you saying 1.1.0 is the last version working or the first version _not_ working?

**Comment by ampersand-five** [comment]
That did not fix it.

**Comment by ampersand-five** [comment]
🤔 I'm having a different error on 1.0.3 now, that, you tell me, if this new error I have is related to the missing dependencies error or not:

`dbt-metabase exposures` runs fine (when I'm using dbt-metabase 1.0.3) with dependencies populated, but when I run `dbt docs generate` I get an error where:
> Exposure 'exposure.ex.__b_example__data' (models/exposures/exposures.yml) depends on a source named 'example.external_api_logs' which was not found

This error, I think, is because:
I have three databases connected in Metabase, let's say database A, B and C. I have dbt configured to only look at database A. In Metabase we have custom SQL questions written for all three. This error is failing on a question in Metabase that is written for database b, which is not in dbt's output because I only have it on database a.

Is this related or different? If it's different I'll make a new issue.

**Comment by gouline** [comment]
Not much I can do without being able to reproduce this, unfortunately. See if you can write a query that exhibits your issue against the [sandbox](https://github.com/gouline/dbt-metabase/tree/master/sandbox) project or your own minimal sample project that you can share as a repository (removing anything proprietary), then I can have a look.

**Comment by gouline** [comment]
To help you troubleshoot, I created a debug branch `exposure-depends-dump` for you to try. This writes dependencies that aren't present in the model lookup as `unknown('table')` in the exposure YAML and creates a debug.yml file with the lookups:

* If `depends_on` are still empty, that means it's not extracting table names from your questions
* If they're full of unknowns, that means it can't find models your the dbt manifest corresponding to the extracted table names

```
pip install git+ssh://git@github.com/gouline/dbt-metabase.git@exposure-depends-dump
```
