### ISSUE TITLE
[FeatureRequest] Generate dbt doc from Metabase

### ISSUE THREAD

**Issue by benjdl** [gouline/dbt-metabase#274]
Hi @gouline, thank you for this great package!

I use it for my client and it works well.
Now, we have a specific case where we would like to pull the documentation from Metabase to automatically generate DBT documentation yml files for the models retrieved.
Do you think this is something feasible? Have you already thought about that feature?

**Comment by gouline** [comment]
Are you talking about retrieving [Metabase models](https://www.metabase.com/learn/metabase-basics/querying-and-dashboards/data-modeling/models) as dbt models?

**Comment by benjdl** [comment]
@gouline No I mean Metabase tables/fields. Import the tables/fields documentation from Metabase and generate dbt documentation files.

**Comment by gouline** [comment]
Doesn't dbt only generate documentation from its models? Do they support "side loading" tables?

**Comment by benjdl** [comment]
As long as you have an empty sql file with its name referenced in the yml documentation file, dbt is able to generate the documentation.
For example I have a `cell.sql` file which is empty, and a `cell.yml` with the following content:
```
version: 2

models:
  - name: cell
    description: A table containing information about all the cells.
```
The command `dbt generate docs` will generate the documentation for this model and it will be visible on the dbt documentation webserver.

**Comment by gouline** [comment]
The purpose of dbt-metabase is synchronising your dbt project into Metabase and back, anything unrelated already there is out of scope. Additionally, it would be a sizeable effort and empty SQL files are somewhat a hack.
