### ISSUE TITLE
URL-encoded filenames for Japanese Metabase collection names in dbt-metabase exposures

### ISSUE THREAD

**Issue by takaHAL** [gouline/dbt-metabase#296]
Nice to meet you and thank you for the great OSS.
I noticed that when using dbt-metabase, if I use Japanese in the filename, it is URL encoded.
Is there a valid option in dbt-metabase to resolve this?

### Description
When using `dbt-metabase` to generate `exposures`, filenames for Metabase collections that contain Japanese characters are URL-encoded. This makes the filenames less readable and harder to manage.

For example:
- Collection name in Metabase: `分析`
- Generated filename: `%E5%88%86%E6%9E%90.yml`

### Expected Behavior
Filenames should use the original characters, retaining their readability:
- Expected filename: `分析.yml`

One potential improvement could be to incorporate `urllib.parse.unquote` during the file generation process to decode the filenames. This might help ensure that the filenames better reflect the original collection names in a more human-readable format.

### Steps to Reproduce
1. Create a collection in Metabase with a Japanese name (e.g., `分析`).
2. Run `dbt-metabase` to generate `exposures`.
3. Check the filenames in the `exposures` directory.

**Comment by yuichi-github-dev** [comment]
I’m facing the same issue.
When a Metabase collection name contains Japanese characters, the file name becomes excessively long after URL encoding, leading to the following error:
```
OSError: [Errno 36] File name too long: 'models/exposures/metabase/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.yml'
```
(Note: The file name has been masked for confidentiality.)
