### ISSUE TITLE
Assume schema is "public" when API returns None

### ISSUE THREAD

**Issue by davideanastasia** [gouline/dbt-metabase#5]
BigQuery doesn't have the concept of schema. For this reason, I am getting a lot of errors on the upper() functions applied to NoneType (this happens when retrieving metadata for tables and fields).

I suggest to assume the schema is `public` when the API returns None.

**Comment by gouline** [comment]
Didn't know that, my primary usage is on Snowflake. But that sounds reasonable, let's do it.
