### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by fernandobrito** [gouline/dbt-metabase#53]
An Issue to keep track of what should be updated in the docs before releasing 0.8.0:

- [ ] Use of `export models` and `export exposures` in the CLI commands

Anything else you are aware?
I can open a PR if needed. I just wanted to do many things in one-go 😄

**Comment by gouline** [comment]
Thanks for raising this, would definitely appreciate a PR for this 👍

**Comment by z3z1ma** [comment]
Hello! 👋 

Correct me if I am wrong but aren't these in the docs?

![image](https://user-images.githubusercontent.com/41213451/131593894-5a6c197b-2162-47ea-86cb-c486ce0b7171.png)

**Comment by fernandobrito** [comment]
@z3z1ma yes, the docs are good, but it's just missing the word `export` in the command example 😄 .

**Comment by gouline** [comment]
I think that's a bug, `export` should have been replaced with `models` and `exposures`. Correct me if I'm wrong @z3z1ma?

**Comment by z3z1ma** [comment]
Ah yes that is exactly right. The commands should simply be `models` and `exposures`
A future command is `metrics` 

Makes it very easy to use. Good catch on that.
