### ISSUE TITLE
Sync table visibility

### ISSUE THREAD

**Issue by mmmatthew** [gouline/dbt-metabase#68]
It would be useful to automatically hide/show models in Metabase. The metabase API endpoint[ `PUT /api/table/:id`](https://www.metabase.com/docs/latest/api-documentation.html#put-apitableid) accepts a `visibility_type` value that may be nil, or if non-nil, value must be one of: `cruft`, `hidden`, `technical`. Can we allow the 
```
  meta:
    metabase.visibility_type: hidden
```
to be defined on models?

**Comment by z3z1ma** [comment]
@gouline 

What we have is field level visibility setting adjustment.

What is available through Metabase and what he is suggesting is _table level_ visibility adjustment. Which makes sense given how dbt proliferates tables/views as models which might not need to be seen or so easily exposed.
The implementation would likely look very similar to what you have already, just scoped to the table endpoint.

**Comment by rarup1** [comment]
@gouline Is this still being worked on or in the plans?

**Comment by gouline** [comment]
Ask @mmmatthew, he's working on #71

**Comment by mmmatthew** [comment]
Sorry, I don't have plans to continue this in the near future. Someone else is welcome to pick it up.
