### ISSUE TITLE
Add support for self-referencing tables

### ISSUE THREAD

**Issue by mmmatthew** [gouline/dbt-metabase#74]
This logic does not account for self-referencing tables: 

https://github.com/gouline/dbt-metabase/blob/e7c7832c473b8d17ad2dd02f402c881e93897332/dbtmetabase/parsers/dbt_manifest.py#L209-L217

**Comment by jmccormick11** [comment]
This is something we are also running into. It seemed  to work when using the `dbt_path` but is now breaking when using the manifest setup
