### ISSUE TITLE
Support meta fields for column type specifications

### ISSUE THREAD

**Issue by Limess** [gouline/dbt-metabase#8]
DBT recently added [`meta`](https://docs.getdbt.com/reference/resource-properties/meta/) definitions for models and columns.

It'd be nice to be able to use these, rather than tests, to specify metabase column types.

Using `meta` would remove any impact on test runtime when running DBT, and remove the need for the DBT package specified in this project.

**Comment by gouline** [comment]
Thanks for raising this, good idea. I'll have a play around and release it at some point in the future.

**Comment by gouline** [comment]
Released in 0.5.0.
