### ISSUE TITLE
Permission System sync

### ISSUE THREAD

**Issue by patygold** [gouline/dbt-metabase#82]
On Metabase, it's possible to define permissions restrictions to tables for certain groups (Such as in the picture)
![image](https://user-images.githubusercontent.com/8875581/146002994-3e5ec0f2-8d0c-4d01-9453-94622edebe25.png)

In the Open Source plan for Metabase, we can define if this group has either "Unrestricted" or "No self-Service" permission to the table, I am not sure if this changes for the other plans.

Is the automation for the permission system, something planned/wanted for this package?

One suggestion that could make it possible is to add this in the `meta` section of the table definition, and define which groups have which level of permission:
![image](https://user-images.githubusercontent.com/8875581/146004546-1852a5df-574a-4b06-86b0-43af1021d76a.png)

**Comment by gouline** [comment]
Definitely not planned and probably a little too far in my opinion - the purpose of dbt-metabase is not to be a fully-featured infrastructure as code tool for Metabase shoehorned into dbt syntax. However, this particular feature is still borderline related to the data models, so if you (or somebody else) were to contribute a pull request implementing it, I wouldn't be against it.

**Comment by rarup1** [comment]
I have come across this problem. My work around is to hold a table within the postgres database (where Metabase metadata is held) with our HR employee table. This updates daily. I then created a function and trigger to call this function whenever the metabase.core_user table is updated/inserted to or the HR data is refreshed. 

Something like this:
```

CREATE TABLE metabase.<company_schema>.employees
(
    id               serial,
    first_name       varchar(50),
    last_name        varchar(50),
    email_address    varchar(100),
    department       varchar(100),
    division         varchar(100),
    metabase_user_id integer,
    refreshed_at     timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION metabase.<company_schema>.assign_group_from_divison() RETURNS trigger AS
$assign_group_from_divison$
BEGIN
    INSERT INTO metabase.public.permissions_group_membership(user_id, group_id)
    SELECT u.id,
           pg.id AS group_id
    FROM metabase.public.core_user u
             LEFT JOIN metabase.<company_schema>.employees em ON em.email_address = u.email
             LEFT JOIN metabase.public.permissions_group pg on pg.name = em.division
             LEFT JOIN metabase.public.permissions_group_membership pgm
                       ON u.id = pgm.user_id AND
                          pgm.group_id = pg.id
    WHERE pgm.group_id IS NULL AND em.email_address IS NOT NULL;
    UPDATE metabase.<company_schema>.employees emp
    SET metabase_user_id = u.id
    FROM metabase.public.core_user u
    WHERE emp.email_address = u.email;
    RETURN NULL;
END;
$assign_group_from_divison$ LANGUAGE plpgsql;

CREATE TRIGGER usp_assign_to_group_from_division_insert
    AFTER INSERT
    ON metabase.public.core_user
EXECUTE PROCEDURE metabase.<company_schema>.assign_group_from_divison();

CREATE TRIGGER usp_assign_to_group_from_division_insert
    AFTER INSERT
    ON metabase.<company_schema>.employees
EXECUTE PROCEDURE metabase.<company_schema>.assign_group_from_divison();
```

This is higher risk as you are interacting with the production database. We tested this out in a development environment rigorously before using in production.
