### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by soltanianalytics** [gouline/dbt-metabase#84]
I'd wager that the usability and prevalence of this marvelous packages would be greatly advanced if there was a basic documentation to go along with the two major models (`MetabaseInterface` and `DbtInterface`). For instance, it took me a few hours to realize that my implementation wasn't working because `schema` is, in fact, not a mandatory field but rather a field limiting the amount of models being parsed and synced.

I think this is a great tool that is easily usable _if you know how to_, where a bit of docs could go a long way :)

**Comment by gouline** [comment]
Feel free to propose specific improvements. We went as far as we could with the documentation, beyond that you're welcome to PR improvements/corrections.

**Comment by soltanianalytics** [comment]
Solved
