### ISSUE TITLE
Native query parsing for exposures doesn't recognize models with qualified table names.

### ISSUE THREAD

**Issue by jcubed111** [gouline/dbt-metabase#97]
It appears that the code to pull exposures from native queries is unable to recognize model names when they're qualified.

I'd expect the below metabase query to generate an exposure dependent on `my_model`, but it doesn't.
```sql
select * from db.schema.my_model
```

I think the bug is that [the regex](https://github.com/gouline/dbt-metabase/blob/7d9fbbfb5cd2a569838b4b37e85765b5443d8afd/dbtmetabase/metabase.py#L59) used to find `from` and `join` clauses doesn't allow for `.` or `"` characters, despite [the subsequent code](https://github.com/gouline/dbt-metabase/blob/7d9fbbfb5cd2a569838b4b37e85765b5443d8afd/dbtmetabase/metabase.py#L723) appearing to account for those cases.

I'd propose that the regex should instead allow `.` and `"` characters. 
```python
r"[FfJj][RrOo][OoIi][MmNn]\s+\b([\w.\"]+)\b"
```

**Comment by gouline** [comment]
You're welcome to create a pull request and test whether it works for you.

**Comment by z3z1ma** [comment]
This is ready to close @gouline
