### ISSUE TITLE
metabase_use_http argument not being used when specified in config.yml

### ISSUE THREAD

**Issue by jack-cook-repo** [gouline/dbt-metabase#99]
When using a config.yml file and specifying `metabase_use_http: True` (tried upper and lower case), I end up with the following SSL error (**note: running Metabase via `http://localhost:3000`**):

```
requests.exceptions.SSLError: HTTPSConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/session (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1122)')))
```

After digging into it, the issue was that it was still sending the request via `https`. I found that [here](https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/metabase.py#L854-L856) the `self.protocol` attribute was still being passed as `https` resulting in the error.

```
response = requests.request(
            method, f"{self.protocol}://{self.host}{path}", verify=self.verify, **kwargs
        )
```

Using --metabase_http as a command line argument fixed the issue for me, I _believe_ it just overrides what's [here](https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/__init__.py#L236-L241)
```
@click.option(
    "--metabase_http/--metabase_https",
    "metabase_use_http",
    default=False,
    help="use HTTP or HTTPS to connect to Metabase. Default HTTPS",
)
```

Currently using dbt-metabase==0.8.5

**Comment by gouline** [comment]
Entirely possible, I don't think a lot of people use it. You're welcome to submit a pull request, should be easy to fix.

**Comment by jack-cook-repo** [comment]
I've got a fix working, but I seem to be getting a 403 error when pushing my branch to the repo - do I need any permissions set up?

```
remote: Permission to gouline/dbt-metabase.git denied
```

I've tried using SSH and HTTPS and both are giving the same error

**Comment by jack-cook-repo** [comment]
@gouline #100
